x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "12m"
    max-file: "5"

services:
  balancer:
    build: "balancer"
    image: "abrarov/angie-test-balancer"
    ports:
      - "80:8080"
      - "81:8081"
    logging: *default-logging

  backend:
    build: "backend"
    image: "abrarov/angie-test-backend"
    deploy:
      mode: "replicated"
      replicas: 3
    logging: *default-logging
